version: '3.0'
 
services:
    db:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: strong$pwd
       MYSQL_DATABASE: PeopleDB
       MYSQL_USER: docker
       MYSQL_PASSWORD: Docker1@pwd
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     ports:
       - "6603:3306"
     restart: always
     
    memberspa:
     depends_on:
       - db
     image: zhaosimeon/spa-ng-asp-core:v1     
     ports:
       - "8080:5000"
       
volumes:
    dbdata: